version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: db
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      REDIS_HOST: redis  # Added Redis host information
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    ports:
      - "80:80"
      - "5173:5173"
    depends_on:
      - db
      - redis  # Added dependency on the Redis container

  redis:  # Added Redis container
    image: "redis:latest"
    ports:
      - "6379:6379"

  publicip:
    image: dexterquazi/service
    environment:
      HOST: webapp
      PORT: 5173
    depends_on:
      - webapp

volumes:
  sail-mysql:
